### ISSUE TITLE
Toggle on/off

### ISSUE THREAD

**Issue by tringstad** [jfcherng-roundcube/plugin-show-folder-size#13]
When activated, one must leave active page to "unload" foldersize view. Would have been nice to be able to toggle on/off when pressing the same button

**Comment by jfcherng** [comment]
That is conflict with the current design, which is refreshing the folder size.

**Comment by jfcherng** [comment]
I've moved size information into a dedicated popup dialog which looks like the following screenshot in `0.7.0`.

![image](https://user-images.githubusercontent.com/6594915/82545872-d8e60700-9b89-11ea-82b7-2a9cf1795728.png)
