### ISSUE TITLE
Display folders cumulative size instead of 

### ISSUE THREAD

**Issue by rdacn** [jfcherng-roundcube/plugin-show-folder-size#16]
Hello
we plan to use your great plugin in our RC deployment
However, we noticed that the displayed folder size is not cumulative : a folder containing 2 others folders of 5Mb each, but with 3 messages of 1Kb  in the root will be displaying a size of 3 Kb, instead of ~10 Mb, which can be misleading for users. The aim of using this plugin is that users realize how huge some of their folders can be, and we think that without cumulative size, this is partially missed.
Do you think it is possible, or if others prefer root size, have an option in config.inc.php to choose between normal and cumulative size ?
Thanks
PS : if you don't have much time I can have a look (I used to be a dev) and submit some code

**Comment by jfcherng** [comment]
Yeah. At this moment, It just shows what RC's API reports without any other calculation. It would be good to display accumulated size as well.

![image](https://user-images.githubusercontent.com/6594915/84127077-573f1600-aa71-11ea-9987-14b6af871537.png)

I guess we can calculate accumulated ones and display them in another column.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/84139141-ee13ce80-aa81-11ea-9f71-e7e5d3ba6501.png)

Done in https://github.com/jfcherng-roundcube/plugin-show-folder-size/commit/9962ac7d7fb084ebf361e86aae5d40a60a3944d7.

**Comment by rdacn** [comment]
Awesome ! Thanks !
