### ISSUE TITLE
JS Bug with hidden folders in 0.7.5 (dialog box not showing)

### ISSUE THREAD

**Issue by rdacn** [jfcherng-roundcube/plugin-show-folder-size#20]
Hi 
some users noticed that "Show folder size" didn't work with them
A console debug showed a JS error

TypeError: y is undefined
    plugins/show_folder_size/assets/main.min.js?s=1591806853:42

Pointing to : 
 class="name '.concat(y.virtual...   ==> where error is thrown
and 
y = a.env.mailboxes[c]      ==> where y is defined (line 41 just before)

I guessed it had to do with hidden folders
On closer inspection it seems to be related to this : the error occurs when a folder is hidden (or not marked as "subscribed" in the imap account)
On a test account, if I go to Settings->Folders and hide the folder : 
![image](https://user-images.githubusercontent.com/36893452/84908296-96deb100-b0b4-11ea-871a-4aa5e2c37661.png)

Then the error occurs
If I toggle to show the folder, the error disappears and the dialog box shows

**Comment by jfcherng** [comment]
Ok. I am able to reproduce with a unsubscribed mailbox.

**Comment by jfcherng** [comment]
Fixed with https://github.com/jfcherng-roundcube/plugin-show-folder-size/commit/ed97a2c6040da562c18e3b7080ab419cb45b87ad. `0.7.6` has been released.

**Comment by rdacn** [comment]
Great ! Thanks a lot !
BTW, are you interested in fr_FR localization file ?

**Comment by jfcherng** [comment]
> BTW, are you interested in fr_FR localization file ?

Why not :smile:

**Comment by rdacn** [comment]
Here you are, if it can help : 

<?php

$labels = [];

$labels['show_folder_size (plugin name)'] = 'Taille des dossiers';

// UI button
$labels['show_folder_size'] = 'Taille des dossiers';

// popup dialog
$labels['folder_size'] = 'Taille des dossiers';
$labels['name'] = 'Nom';
$labels['size'] = 'Taille';
$labels['cumulative_size'] = 'Taille (Cumulative)';

**Comment by rdacn** [comment]
$labels = [];

$labels['show_folder_size (plugin name)'] = 'Taille des dossiers';

// UI button
$labels['show_folder_size'] = 'Taille des dossiers';

// popup dialog
$labels['folder_size'] = 'Taille des dossiers';
$labels['name'] = 'Nom';
$labels['size'] = 'Taille';
$labels['cumulative_size'] = 'Taille (Cumulative)';

**Comment by jfcherng** [comment]
> Here you are, if it can help :

Great. Thanks. `0.7.7` has been released.
