### ISSUE TITLE
Unable to show anything after click on button

### ISSUE THREAD

**Issue by julian70400** [jfcherng-roundcube/plugin-show-folder-size#22]
Roundcube Webmail 1.3.15 (1.3.15+dfsg.1-1~deb10u1)
PHP 7.3
nginx version: nginx/1.14.2
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
show-folder-size | 0.7.7

Hello,

Just installed your plugin, but after active it, when I click on the button to show sizes, nothing happened.

Nothing in nginx logs, nothing also in roundcube log. On Chrome, dev mode just showing me this : 

GET https://webmail.mydomain.org/plugins/show_folder_size/skins/larry/main.css?s=1598258856 net::ERR_ABORTED 404 (Not Found)
2webmail.mydomain.org/:138 GET https://webmail.mydomain.org/plugins/show_folder_size/assets/main.min.js?s=1598258856 net::ERR_ABORTED 404 (Not Found)

Nothing else. 

What should I do ? Thanks

**Comment by jfcherng** [comment]
Do those files actually exist with a correct path on the filesystem?

If yes but it's not publicly accessible, then it's a NGINX configuration problem I guess.

**Comment by julian70400** [comment]
Do those files actually exist with a correct path on the filesystem?
==> they do, with corrects rights
If yes but it's not publicly accessible, then it's a NGINX configuration problem I guess.
==> all my others plugins works fine with the current configuration, nginx can access to every files

**Comment by jfcherng** [comment]
> ==> all my others plugins works fine with the current configuration, nginx can access to every files

In this case, could you manually write a correct URL to access say `main.min.js`?

**Comment by julian70400** [comment]
sorry, I did not understand. Where should I write this url in this file ?

Thanks for your help.

**Comment by jfcherng** [comment]
> nginx can access to every files

I mean could you manually construct a URL to access the `main.min.js` file of this plugin, given that you said there is no permission or NGINX configuration problem.

**Comment by julian70400** [comment]
Ok understood.
Well : 
- https://webmail.mydomain.org/plugins/show_folder_size/assets/main.min.js?s=1598258856
- https://webmail.mydomain.org/plugins/show_folder_size/skins/larry/main.css?s=1598258856

==> file not found

That's really strange.. 

*.*.*.* - - [24/Aug/2020:11:58:31 +0200] "GET /plugins/show_folder_size/skins/larry/main.css?s=1598258856 HTTP/1.1" 404 27 "-" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Mobile Safari/537.36"

ls -altrh skins/larry/
total 16K
-rw-r--r-- 1 www-data www-data  126 août  24 10:47 main.less
-rw-r--r-- 1 www-data www-data  316 août  24 10:47 main.css

**Comment by jfcherng** [comment]
This seems to be not a RoundCube-related problem then :thinking: 

So https://webmail.mydomain.org/plugins/hide_blockquote/skins/larry/style.css?s=1598258856 is accessible?

**Comment by julian70400** [comment]
> So https://webmail.mydomain.org/plugins/hide_blockquote/skins/larry/style.css?s=1598258856 is accessible?

Right, it does.

**Comment by jfcherng** [comment]
The last option I can figure out... `$ chmod a+r -R plugins/show_folder_size/`

**Comment by julian70400** [comment]
> The last option I can figure out... `$ chmod a+r -R plugins/show_folder_size/`

Not better, I am absolutely lost. Something like **https://webmail.mydomain.org/plugins/contextmenu/skins/larry/contextmenu.css** works fine, with same rights, but in your case, it doesn't.

Well, I think you helped me as you can, thanks, will check some other things.

**Comment by julian70400** [comment]
Not plugin related issue
