### ISSUE TITLE
New versions not on packagist.org

### ISSUE THREAD

**Issue by GermanCoding** [jfcherng-roundcube/plugin-show-folder-size#26]
While checking my plugin versions, I noticed that composer only installed version 0.7.7 of this plugin, while GitHub/Tags list 0.7.10 as latest release.

A quick check on https://packagist.org/packages/jfcherng-roundcube/show-folder-size shows that they see 0.7.7 as latest version and are unaware of more recent releases.

**Comment by jfcherng** [comment]
Thanks. Didn't notice that... It has been fixed now.
