### ISSUE TITLE
error with folder names with only numbers

### ISSUE THREAD

**Issue by nodo50** [jfcherng-roundcube/plugin-show-folder-size#29]
Hi, if I have a mail folder with only numbers in the name I get a error 500 when click on Show folder sizes.
Only happens when it is a top level folder.
Plugin version: 0.7.14
PHP version: 7.4.28

The PHP error is:

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to show_folder_size::isFolderParentAndChild() must be of the type string, int given, called in /var/www/roundcubemail/plugins/show_folder_size/show_folder_size.php on line 142 and defined in /var/www/roundcubemail/plugins/show_folder_size/show_folder_size.php:171
#0 /var/www/roundcubemail/plugins/show_folder_size/show_folder_size.php(142): show_folder_size->isFolderParentAndChild()
#1 /var/www/roundcubemail/plugins/show_folder_size/show_folder_size.php(104): how_folder_size->calcualteCumulativeSizes()
#2 /var/www/roundcubemail/plugins/show_folder_size/show_folder_size.php(64): show_folder_size->getFolderSizes()
#3 /var/www/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(522): show_folder_size->getFolderSizeAction()
#4 /var/www/roundcubemail/index.php(292): rcube_plugin_api->exec_action()  thrown in /var/www/roundcubemail/plugins/show_folder_size/show_folder_size.php on line 171

**Comment by jfcherng** [comment]
Thanks. I can reproduce this.

**Comment by jfcherng** [comment]
`0.7.15` has been released and it should fix this.

**Comment by nodo50** [comment]
Great! thank you very much for that fast fix. Installed and working fine.
