### ISSUE TITLE
All folders total size

### ISSUE THREAD

**Issue by v20z** [jfcherng-roundcube/plugin-show-folder-size#41]
Hello and thanks for your plugin.

If it is not difficult please add opportunity to show all folders total size with emphasized text/font in the summary line at the very bottom

Thank You.

**Comment by jfcherng** [comment]
You mean a new row like this?
![image](https://github.com/jfcherng-roundcube/plugin-show-folder-size/assets/6594915/d43d5126-b9cd-42fb-adb0-8ca8fe88c325)

**Comment by v20z** [comment]
Yes, that is right, you got it exactly right.

Thank You.

**Comment by jfcherng** [comment]
Done and released in v0.7.20.
